steps:
  # Copy down the model
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |      
        gsutil cp gs://arxiv-classifier-dev-models/models.tar.xz models.tar.xz
        xz --decompress models.tar.xz
        tar xf models.tar
  # Do the docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
    '--build-arg', 'git_commit=$SHORT_SHA',
    '-t', 'gcr.io/arxiv-classifier/classifier',
    '--label', 'git-commit=$SHORT_SHA',
    '--label', 'github-repo=$REPO_NAME',
    '.' ]
  # Deploy to GCP
  # Zone us-east1-d chosen for no specific reason
  # Instance name must start with a-z and be in [a-z0-9-]
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    args: ['compute', 'instances', 'update-container',
    'classifier-vm' ,
    '--zone', 'us-east1-d',
    '--container-image',
    'gcr.io/arxiv-classifier/classifier:latest']

images: ['gcr.io/arxiv-classifier/classifier']
