steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |      
        gsutil cp gs://arxiv-classifier-dev-models/models.tar.xz models.tar.xz
        xz --decompress models.tar.xz
        tar xf models.tar

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
    '--build-arg', 'git_commit=$SHORT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/classifier',
    '--label', 'git-commit=$SHORT_SHA',
    '--label', 'github-repo=$REPO_NAME',
    '.' ]

images: ['gcr.io/$PROJECT_ID/classifier']
